
stages:
  - tests
  - dockerize

variables:
  TARGETARCH:
    value: "linux"
    options:
      - "linux"
      - "macos"
    description: "Pick OS"
  TARGETOS:
    value: "amd64"
    options:
      - "amd64"
      - "arm64"
    description: "Pick ARCH"
  REPO: "https://git.larkin.com.ua/vlarkin/chatbot"
  DOCKER_REGISTRY: "ghcr.io/vlarkin"
  BRANCH: "master"

tests-job:
  stage: tests
  script:
    - echo "Run tests ..."
    - make tests

docker-job:
  stage: dockerize
  before_script:
    - echo $GITHUB_TOKEN | docker login $DOCKER_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - echo "Build and push a docker image"
    - make dockerize
  after_script:
    - make clean && docker system prune -a --volumes --force
  needs:
    - tests-job

