apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kbot
  labels:
    app: kbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kbot
  template:
    metadata:
      labels:
        app: kbot
    spec:
      containers:
        - name: kbot
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}-{{ .Values.image.os }}-{{ .Values.image.arch }}
          ports:
            - containerPort: 8080
