apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      imagePullSecrets:
        - {{ .Values.image.pullSecret }}
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.version }}-{{ .Values.image.os }}-{{ .Values.image.arch }}
          ports:
            - containerPort: 8080
