replicaCount: 1
#
image:
  pullSecrets: "artifact-registry"
  registry: "europe-docker.pkg.dev/skillful-fx-417519/docker-images"
  repository: "chatbot"
  tag: "v1.0.0-be507b4"
  os: "linux"
  arch: "amd64"
#
secret:
  name: "chatbot"
  env: "TELE_TOKEN"
  key: "token"
  value: ""
