replicaCount: 1
#
image:
  registry: "ghcr.io"
  repository: "den-vasyliev/kbot"
  tag: "v1.0.0-106879e"
  os: "linux"
  arch: "amd64"
#
secret:
  name: "chatbot"
  env: "TELE_TOKEN"
  key: "token"
  value: ""
