#
appName: chatbot
#
replicaCount: 1
#
imagePullSecrets:
  - name: docker-registry
image:
  registry: ghcr.io
  repository: vlarkin/chatbot
  tag: v1.0.0-046d86a
  os: linux
  arch: amd64
#
secret:
  env: TELE_TOKEN
  name: chatbot
  key: token
  value: ""
