#
appName: chatbot
#
replicaCount: 1
#
image:
  registry: ghcr.io
  repository: vlarkin/chatbot
  tag: v1.0.0-83d1ddb
  os: linux
  arch: amd64
#
secret:
  env: TELE_TOKEN
  name: chatbot
  key: token
  value: ""
