#
appName: "chatbot"
#
replicaCount: 1
#
image:
  pullSecret: "artifact-registry"
  repository: "europe-docker.pkg.dev/skillful-fx-417519/docker-images"
  name: "chatbot"
  version: "v1.0.0-be507b4"
  os: "linux"
  arch: "amd64"
#
secret:
  name: "chatbot"
  env: "TELE_TOKEN"
  key: "token"
  value: ""
