#
appName: chatbot
#
replicaCount: 1
#
image:
  pullSecretName: artifact-registry
  registry: ghcr.io/vlarkin
  name: chatbot
  version: v1.0.0-67c2c10
  os: linux
  arch: amd64
#
secret:
  env: TELE_TOKEN
  name: chatbot
  key: token
  value: ""
