name: Main CI/CD workflow

on: 
  push:
    branches:
      - develop

env:
  TARGETOS: linux
  TARGETARCH: amd64
  DOCKER_REGISTRY: ghcr.io/vlarkin

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: GitHub Container Registry login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push a docker image
        run: make dockerize
  cd:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set VERSION variable
        run: echo "VERSION=$(git describe --tags --abbrev=0 --always)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Update helm/values.yaml
        uses: mikefarah/yq@master
        with:
          cmd: >-
            yq -i ".image.tag=strenv(VERSION) | .image.os=strenv(TARGETOS) | 
                   .image.arch=strenv(TARGETARCH) | .image.registry=strenv(DOCKER_REGISTRY)" helm/values.yaml
      - name: Push changes to the repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Update helm/values.yaml"
          git push
