name: Main CI/CD workflow

on: 
  push:
    branches:
      - develop

env:
  TARGETOS: linux
  TARGETARCH: amd64
  DOCKER_REGISTRY: ghcr.io/vlarkin

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: GitHub Container Registry login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push a docker image
        run: make dockerize
  cd:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Set version
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        run: echo "VERSION=$(git describe --tags --abbrev=0 --always)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Update helm/values.yaml
        uses: mikefarah/yq@master
        run: |
          yq -i ".image.version=$VERSION | .image.os=$TARGETOS | .image.arch=$TARGETARCH" helm/values.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Update helm/values.yaml"
          git push
