name: Main CI/CD workflow

on: 
  push:
    branches:
      - develop

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run tests
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.58.1
        run: make lint
      - name: GitHub Container Registry login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push a docker image
        env:
          TARGETOS: linux
          TARGETARCH: amd64
          DOCKER_REGISTRY: ghcr.io/vlarkin
        run: make dockerize
